/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YtstreamRouteImport } from './routes/ytstream'
import { Route as YtdlRouteImport } from './routes/ytdl'
import { Route as XRouteImport } from './routes/x'
import { Route as WabotRouteImport } from './routes/wabot'
import { Route as TempmailRouteImport } from './routes/tempmail'
import { Route as TempchatRouteImport } from './routes/tempchat'
import { Route as ShsdbConsoleRouteImport } from './routes/shsdb-console'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as NoteRouteImport } from './routes/note'
import { Route as MoreRouteImport } from './routes/more'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MainRouteImport } from './routes/main'
import { Route as LinksRouteImport } from './routes/links'
import { Route as IsraelRouteImport } from './routes/israel'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as HostingRouteImport } from './routes/hosting'
import { Route as HeliumRouteImport } from './routes/helium'
import { Route as GitnetworkRouteImport } from './routes/gitnetwork'
import { Route as DbConsoleRouteImport } from './routes/db-console'
import { Route as ConvertRouteImport } from './routes/convert'
import { Route as CloudifyRouteImport } from './routes/cloudify'
import { Route as ClipboardRouteImport } from './routes/clipboard'
import { Route as ApiServicesRouteImport } from './routes/api-services'
import { Route as AiImageRouteImport } from './routes/ai-image'
import { Route as FilenameRouteImport } from './routes/$filename'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoteIndexRouteImport } from './routes/note.index'
import { Route as FiIndexRouteImport } from './routes/fi.index'
import { Route as ShsdbCreateRouteImport } from './routes/shsdb.create'
import { Route as ShsdbIdRouteImport } from './routes/shsdb.$id'
import { Route as NoteNoteIdRouteImport } from './routes/note.$noteId'
import { Route as FiSplatRouteImport } from './routes/fi.$'
import { Route as DbCreateRouteImport } from './routes/db.create'
import { Route as DbIdRouteImport } from './routes/db.$id'
import { Route as ApiYtstreamSearchRouteImport } from './routes/api/ytstream/search'
import { Route as ApiYtdlDownloadRouteImport } from './routes/api/ytdl/download'
import { Route as ApiXUserRouteImport } from './routes/api/x/user'
import { Route as ApiXTweetsRouteImport } from './routes/api/x/tweets'
import { Route as ApiXDownloadRouteImport } from './routes/api/x/download'
import { Route as ApiWabotManageRouteImport } from './routes/api/wabot/manage'
import { Route as ApiV1Ytv3RouteImport } from './routes/api/v1/ytv3'
import { Route as ApiV1InstagramRouteImport } from './routes/api/v1/instagram'
import { Route as ApiV1ImageRouteImport } from './routes/api/v1/image'
import { Route as ApiV1AiRouteImport } from './routes/api/v1/ai'
import { Route as ApiPublicUploadRouteImport } from './routes/api/public/upload'
import { Route as ApiPublicDownloadRouteImport } from './routes/api/public/download'
import { Route as ApiPfpUploadRouteImport } from './routes/api/pfp/upload'
import { Route as ApiPfpRemoveRouteImport } from './routes/api/pfp/remove'
import { Route as ApiPfpGetRouteImport } from './routes/api/pfp/get'
import { Route as ApiMessagesUpdateprofileRouteImport } from './routes/api/messages/updateprofile'
import { Route as ApiMessagesUpdatepfpRouteImport } from './routes/api/messages/updatepfp'
import { Route as ApiMessagesSendRouteImport } from './routes/api/messages/send'
import { Route as ApiMessagesRegisterRouteImport } from './routes/api/messages/register'
import { Route as ApiMessagesPublickeyRouteImport } from './routes/api/messages/publickey'
import { Route as ApiMessagesPostRouteImport } from './routes/api/messages/post'
import { Route as ApiMessagesListRouteImport } from './routes/api/messages/list'
import { Route as ApiMessagesFeedRouteImport } from './routes/api/messages/feed'
import { Route as ApiMessagesActionRouteImport } from './routes/api/messages/action'
import { Route as ApiLinksManageRouteImport } from './routes/api/links/manage'
import { Route as ApiInstagramDownloadRouteImport } from './routes/api/instagram/download'
import { Route as ApiImageGenerateRouteImport } from './routes/api/image/generate'
import { Route as ApiGitnetworkV1RouteImport } from './routes/api/gitnetwork/v1'
import { Route as ApiGitnetworkManageRouteImport } from './routes/api/gitnetwork/manage'
import { Route as ApiFiUploadRouteImport } from './routes/api/fi/upload'
import { Route as ApiFiDownloadRouteImport } from './routes/api/fi/download'
import { Route as ApiCrossdeviceSendRouteImport } from './routes/api/crossdevice/send'
import { Route as ApiCrossdeviceReceiveRouteImport } from './routes/api/crossdevice/receive'
import { Route as ApiCloudifyUpdateRouteImport } from './routes/api/cloudify/update'
import { Route as ApiCloudifySongsRouteImport } from './routes/api/cloudify/songs'
import { Route as ApiCloudifySearchRouteImport } from './routes/api/cloudify/search'
import { Route as ApiCloudifyDeleteRouteImport } from './routes/api/cloudify/delete'
import { Route as ApiCloudifyCreateRouteImport } from './routes/api/cloudify/create'
import { Route as ApiChatUploadRouteImport } from './routes/api/chat/upload'
import { Route as ApiChatRoomRouteImport } from './routes/api/chat/room'
import { Route as ApiAccountsLoginRouteImport } from './routes/api/accounts/login'
import { Route as ApiAccountsHistoryRouteImport } from './routes/api/accounts/history'
import { Route as ApiAccountsCreateRouteImport } from './routes/api/accounts/create'
import { Route as ApiMessagesFeedLikeRouteImport } from './routes/api/messages/feed/like'
import { Route as ApiMessagesFeedCommentRouteImport } from './routes/api/messages/feed/comment'

const YtstreamRoute = YtstreamRouteImport.update({
  id: '/ytstream',
  path: '/ytstream',
  getParentRoute: () => rootRouteImport,
} as any)
const YtdlRoute = YtdlRouteImport.update({
  id: '/ytdl',
  path: '/ytdl',
  getParentRoute: () => rootRouteImport,
} as any)
const XRoute = XRouteImport.update({
  id: '/x',
  path: '/x',
  getParentRoute: () => rootRouteImport,
} as any)
const WabotRoute = WabotRouteImport.update({
  id: '/wabot',
  path: '/wabot',
  getParentRoute: () => rootRouteImport,
} as any)
const TempmailRoute = TempmailRouteImport.update({
  id: '/tempmail',
  path: '/tempmail',
  getParentRoute: () => rootRouteImport,
} as any)
const TempchatRoute = TempchatRouteImport.update({
  id: '/tempchat',
  path: '/tempchat',
  getParentRoute: () => rootRouteImport,
} as any)
const ShsdbConsoleRoute = ShsdbConsoleRouteImport.update({
  id: '/shsdb-console',
  path: '/shsdb-console',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteRoute = NoteRouteImport.update({
  id: '/note',
  path: '/note',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const IsraelRoute = IsraelRouteImport.update({
  id: '/israel',
  path: '/israel',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const HostingRoute = HostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const HeliumRoute = HeliumRouteImport.update({
  id: '/helium',
  path: '/helium',
  getParentRoute: () => rootRouteImport,
} as any)
const GitnetworkRoute = GitnetworkRouteImport.update({
  id: '/gitnetwork',
  path: '/gitnetwork',
  getParentRoute: () => rootRouteImport,
} as any)
const DbConsoleRoute = DbConsoleRouteImport.update({
  id: '/db-console',
  path: '/db-console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertRoute = ConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudifyRoute = CloudifyRouteImport.update({
  id: '/cloudify',
  path: '/cloudify',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipboardRoute = ClipboardRouteImport.update({
  id: '/clipboard',
  path: '/clipboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServicesRoute = ApiServicesRouteImport.update({
  id: '/api-services',
  path: '/api-services',
  getParentRoute: () => rootRouteImport,
} as any)
const AiImageRoute = AiImageRouteImport.update({
  id: '/ai-image',
  path: '/ai-image',
  getParentRoute: () => rootRouteImport,
} as any)
const FilenameRoute = FilenameRouteImport.update({
  id: '/$filename',
  path: '/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteIndexRoute = NoteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NoteRoute,
} as any)
const FiIndexRoute = FiIndexRouteImport.update({
  id: '/fi/',
  path: '/fi/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShsdbCreateRoute = ShsdbCreateRouteImport.update({
  id: '/shsdb/create',
  path: '/shsdb/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ShsdbIdRoute = ShsdbIdRouteImport.update({
  id: '/shsdb/$id',
  path: '/shsdb/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteNoteIdRoute = NoteNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => NoteRoute,
} as any)
const FiSplatRoute = FiSplatRouteImport.update({
  id: '/fi/$',
  path: '/fi/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DbCreateRoute = DbCreateRouteImport.update({
  id: '/db/create',
  path: '/db/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DbIdRoute = DbIdRouteImport.update({
  id: '/db/$id',
  path: '/db/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYtstreamSearchRoute = ApiYtstreamSearchRouteImport.update({
  id: '/api/ytstream/search',
  path: '/api/ytstream/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYtdlDownloadRoute = ApiYtdlDownloadRouteImport.update({
  id: '/api/ytdl/download',
  path: '/api/ytdl/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXUserRoute = ApiXUserRouteImport.update({
  id: '/api/x/user',
  path: '/api/x/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXTweetsRoute = ApiXTweetsRouteImport.update({
  id: '/api/x/tweets',
  path: '/api/x/tweets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXDownloadRoute = ApiXDownloadRouteImport.update({
  id: '/api/x/download',
  path: '/api/x/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWabotManageRoute = ApiWabotManageRouteImport.update({
  id: '/api/wabot/manage',
  path: '/api/wabot/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Ytv3Route = ApiV1Ytv3RouteImport.update({
  id: '/api/v1/ytv3',
  path: '/api/v1/ytv3',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1InstagramRoute = ApiV1InstagramRouteImport.update({
  id: '/api/v1/instagram',
  path: '/api/v1/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ImageRoute = ApiV1ImageRouteImport.update({
  id: '/api/v1/image',
  path: '/api/v1/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AiRoute = ApiV1AiRouteImport.update({
  id: '/api/v1/ai',
  path: '/api/v1/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadRoute = ApiPublicUploadRouteImport.update({
  id: '/api/public/upload',
  path: '/api/public/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadRoute = ApiPublicDownloadRouteImport.update({
  id: '/api/public/download',
  path: '/api/public/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPfpUploadRoute = ApiPfpUploadRouteImport.update({
  id: '/api/pfp/upload',
  path: '/api/pfp/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPfpRemoveRoute = ApiPfpRemoveRouteImport.update({
  id: '/api/pfp/remove',
  path: '/api/pfp/remove',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPfpGetRoute = ApiPfpGetRouteImport.update({
  id: '/api/pfp/get',
  path: '/api/pfp/get',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesUpdateprofileRoute =
  ApiMessagesUpdateprofileRouteImport.update({
    id: '/api/messages/updateprofile',
    path: '/api/messages/updateprofile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMessagesUpdatepfpRoute = ApiMessagesUpdatepfpRouteImport.update({
  id: '/api/messages/updatepfp',
  path: '/api/messages/updatepfp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesSendRoute = ApiMessagesSendRouteImport.update({
  id: '/api/messages/send',
  path: '/api/messages/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesRegisterRoute = ApiMessagesRegisterRouteImport.update({
  id: '/api/messages/register',
  path: '/api/messages/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesPublickeyRoute = ApiMessagesPublickeyRouteImport.update({
  id: '/api/messages/publickey',
  path: '/api/messages/publickey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesPostRoute = ApiMessagesPostRouteImport.update({
  id: '/api/messages/post',
  path: '/api/messages/post',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesListRoute = ApiMessagesListRouteImport.update({
  id: '/api/messages/list',
  path: '/api/messages/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesFeedRoute = ApiMessagesFeedRouteImport.update({
  id: '/api/messages/feed',
  path: '/api/messages/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesActionRoute = ApiMessagesActionRouteImport.update({
  id: '/api/messages/action',
  path: '/api/messages/action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinksManageRoute = ApiLinksManageRouteImport.update({
  id: '/api/links/manage',
  path: '/api/links/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstagramDownloadRoute = ApiInstagramDownloadRouteImport.update({
  id: '/api/instagram/download',
  path: '/api/instagram/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageGenerateRoute = ApiImageGenerateRouteImport.update({
  id: '/api/image/generate',
  path: '/api/image/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitnetworkV1Route = ApiGitnetworkV1RouteImport.update({
  id: '/api/gitnetwork/v1',
  path: '/api/gitnetwork/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitnetworkManageRoute = ApiGitnetworkManageRouteImport.update({
  id: '/api/gitnetwork/manage',
  path: '/api/gitnetwork/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFiUploadRoute = ApiFiUploadRouteImport.update({
  id: '/api/fi/upload',
  path: '/api/fi/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFiDownloadRoute = ApiFiDownloadRouteImport.update({
  id: '/api/fi/download',
  path: '/api/fi/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrossdeviceSendRoute = ApiCrossdeviceSendRouteImport.update({
  id: '/api/crossdevice/send',
  path: '/api/crossdevice/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrossdeviceReceiveRoute = ApiCrossdeviceReceiveRouteImport.update({
  id: '/api/crossdevice/receive',
  path: '/api/crossdevice/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudifyUpdateRoute = ApiCloudifyUpdateRouteImport.update({
  id: '/api/cloudify/update',
  path: '/api/cloudify/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudifySongsRoute = ApiCloudifySongsRouteImport.update({
  id: '/api/cloudify/songs',
  path: '/api/cloudify/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudifySearchRoute = ApiCloudifySearchRouteImport.update({
  id: '/api/cloudify/search',
  path: '/api/cloudify/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudifyDeleteRoute = ApiCloudifyDeleteRouteImport.update({
  id: '/api/cloudify/delete',
  path: '/api/cloudify/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudifyCreateRoute = ApiCloudifyCreateRouteImport.update({
  id: '/api/cloudify/create',
  path: '/api/cloudify/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatUploadRoute = ApiChatUploadRouteImport.update({
  id: '/api/chat/upload',
  path: '/api/chat/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoomRoute = ApiChatRoomRouteImport.update({
  id: '/api/chat/room',
  path: '/api/chat/room',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsLoginRoute = ApiAccountsLoginRouteImport.update({
  id: '/api/accounts/login',
  path: '/api/accounts/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsHistoryRoute = ApiAccountsHistoryRouteImport.update({
  id: '/api/accounts/history',
  path: '/api/accounts/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsCreateRoute = ApiAccountsCreateRouteImport.update({
  id: '/api/accounts/create',
  path: '/api/accounts/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesFeedLikeRoute = ApiMessagesFeedLikeRouteImport.update({
  id: '/like',
  path: '/like',
  getParentRoute: () => ApiMessagesFeedRoute,
} as any)
const ApiMessagesFeedCommentRoute = ApiMessagesFeedCommentRouteImport.update({
  id: '/comment',
  path: '/comment',
  getParentRoute: () => ApiMessagesFeedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$filename': typeof FilenameRoute
  '/ai-image': typeof AiImageRoute
  '/api-services': typeof ApiServicesRoute
  '/clipboard': typeof ClipboardRoute
  '/cloudify': typeof CloudifyRoute
  '/convert': typeof ConvertRoute
  '/db-console': typeof DbConsoleRoute
  '/gitnetwork': typeof GitnetworkRoute
  '/helium': typeof HeliumRoute
  '/hosting': typeof HostingRoute
  '/instagram': typeof InstagramRoute
  '/israel': typeof IsraelRoute
  '/links': typeof LinksRoute
  '/main': typeof MainRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/note': typeof NoteRouteWithChildren
  '/owner': typeof OwnerRoute
  '/shsdb-console': typeof ShsdbConsoleRoute
  '/tempchat': typeof TempchatRoute
  '/tempmail': typeof TempmailRoute
  '/wabot': typeof WabotRoute
  '/x': typeof XRoute
  '/ytdl': typeof YtdlRoute
  '/ytstream': typeof YtstreamRoute
  '/db/$id': typeof DbIdRoute
  '/db/create': typeof DbCreateRoute
  '/fi/$': typeof FiSplatRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/shsdb/$id': typeof ShsdbIdRoute
  '/shsdb/create': typeof ShsdbCreateRoute
  '/fi/': typeof FiIndexRoute
  '/note/': typeof NoteIndexRoute
  '/api/accounts/create': typeof ApiAccountsCreateRoute
  '/api/accounts/history': typeof ApiAccountsHistoryRoute
  '/api/accounts/login': typeof ApiAccountsLoginRoute
  '/api/chat/room': typeof ApiChatRoomRoute
  '/api/chat/upload': typeof ApiChatUploadRoute
  '/api/cloudify/create': typeof ApiCloudifyCreateRoute
  '/api/cloudify/delete': typeof ApiCloudifyDeleteRoute
  '/api/cloudify/search': typeof ApiCloudifySearchRoute
  '/api/cloudify/songs': typeof ApiCloudifySongsRoute
  '/api/cloudify/update': typeof ApiCloudifyUpdateRoute
  '/api/crossdevice/receive': typeof ApiCrossdeviceReceiveRoute
  '/api/crossdevice/send': typeof ApiCrossdeviceSendRoute
  '/api/fi/download': typeof ApiFiDownloadRoute
  '/api/fi/upload': typeof ApiFiUploadRoute
  '/api/gitnetwork/manage': typeof ApiGitnetworkManageRoute
  '/api/gitnetwork/v1': typeof ApiGitnetworkV1Route
  '/api/image/generate': typeof ApiImageGenerateRoute
  '/api/instagram/download': typeof ApiInstagramDownloadRoute
  '/api/links/manage': typeof ApiLinksManageRoute
  '/api/messages/action': typeof ApiMessagesActionRoute
  '/api/messages/feed': typeof ApiMessagesFeedRouteWithChildren
  '/api/messages/list': typeof ApiMessagesListRoute
  '/api/messages/post': typeof ApiMessagesPostRoute
  '/api/messages/publickey': typeof ApiMessagesPublickeyRoute
  '/api/messages/register': typeof ApiMessagesRegisterRoute
  '/api/messages/send': typeof ApiMessagesSendRoute
  '/api/messages/updatepfp': typeof ApiMessagesUpdatepfpRoute
  '/api/messages/updateprofile': typeof ApiMessagesUpdateprofileRoute
  '/api/pfp/get': typeof ApiPfpGetRoute
  '/api/pfp/remove': typeof ApiPfpRemoveRoute
  '/api/pfp/upload': typeof ApiPfpUploadRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/v1/ai': typeof ApiV1AiRoute
  '/api/v1/image': typeof ApiV1ImageRoute
  '/api/v1/instagram': typeof ApiV1InstagramRoute
  '/api/v1/ytv3': typeof ApiV1Ytv3Route
  '/api/wabot/manage': typeof ApiWabotManageRoute
  '/api/x/download': typeof ApiXDownloadRoute
  '/api/x/tweets': typeof ApiXTweetsRoute
  '/api/x/user': typeof ApiXUserRoute
  '/api/ytdl/download': typeof ApiYtdlDownloadRoute
  '/api/ytstream/search': typeof ApiYtstreamSearchRoute
  '/api/messages/feed/comment': typeof ApiMessagesFeedCommentRoute
  '/api/messages/feed/like': typeof ApiMessagesFeedLikeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$filename': typeof FilenameRoute
  '/ai-image': typeof AiImageRoute
  '/api-services': typeof ApiServicesRoute
  '/clipboard': typeof ClipboardRoute
  '/cloudify': typeof CloudifyRoute
  '/convert': typeof ConvertRoute
  '/db-console': typeof DbConsoleRoute
  '/gitnetwork': typeof GitnetworkRoute
  '/helium': typeof HeliumRoute
  '/hosting': typeof HostingRoute
  '/instagram': typeof InstagramRoute
  '/israel': typeof IsraelRoute
  '/links': typeof LinksRoute
  '/main': typeof MainRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/owner': typeof OwnerRoute
  '/shsdb-console': typeof ShsdbConsoleRoute
  '/tempchat': typeof TempchatRoute
  '/tempmail': typeof TempmailRoute
  '/wabot': typeof WabotRoute
  '/x': typeof XRoute
  '/ytdl': typeof YtdlRoute
  '/ytstream': typeof YtstreamRoute
  '/db/$id': typeof DbIdRoute
  '/db/create': typeof DbCreateRoute
  '/fi/$': typeof FiSplatRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/shsdb/$id': typeof ShsdbIdRoute
  '/shsdb/create': typeof ShsdbCreateRoute
  '/fi': typeof FiIndexRoute
  '/note': typeof NoteIndexRoute
  '/api/accounts/create': typeof ApiAccountsCreateRoute
  '/api/accounts/history': typeof ApiAccountsHistoryRoute
  '/api/accounts/login': typeof ApiAccountsLoginRoute
  '/api/chat/room': typeof ApiChatRoomRoute
  '/api/chat/upload': typeof ApiChatUploadRoute
  '/api/cloudify/create': typeof ApiCloudifyCreateRoute
  '/api/cloudify/delete': typeof ApiCloudifyDeleteRoute
  '/api/cloudify/search': typeof ApiCloudifySearchRoute
  '/api/cloudify/songs': typeof ApiCloudifySongsRoute
  '/api/cloudify/update': typeof ApiCloudifyUpdateRoute
  '/api/crossdevice/receive': typeof ApiCrossdeviceReceiveRoute
  '/api/crossdevice/send': typeof ApiCrossdeviceSendRoute
  '/api/fi/download': typeof ApiFiDownloadRoute
  '/api/fi/upload': typeof ApiFiUploadRoute
  '/api/gitnetwork/manage': typeof ApiGitnetworkManageRoute
  '/api/gitnetwork/v1': typeof ApiGitnetworkV1Route
  '/api/image/generate': typeof ApiImageGenerateRoute
  '/api/instagram/download': typeof ApiInstagramDownloadRoute
  '/api/links/manage': typeof ApiLinksManageRoute
  '/api/messages/action': typeof ApiMessagesActionRoute
  '/api/messages/feed': typeof ApiMessagesFeedRouteWithChildren
  '/api/messages/list': typeof ApiMessagesListRoute
  '/api/messages/post': typeof ApiMessagesPostRoute
  '/api/messages/publickey': typeof ApiMessagesPublickeyRoute
  '/api/messages/register': typeof ApiMessagesRegisterRoute
  '/api/messages/send': typeof ApiMessagesSendRoute
  '/api/messages/updatepfp': typeof ApiMessagesUpdatepfpRoute
  '/api/messages/updateprofile': typeof ApiMessagesUpdateprofileRoute
  '/api/pfp/get': typeof ApiPfpGetRoute
  '/api/pfp/remove': typeof ApiPfpRemoveRoute
  '/api/pfp/upload': typeof ApiPfpUploadRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/v1/ai': typeof ApiV1AiRoute
  '/api/v1/image': typeof ApiV1ImageRoute
  '/api/v1/instagram': typeof ApiV1InstagramRoute
  '/api/v1/ytv3': typeof ApiV1Ytv3Route
  '/api/wabot/manage': typeof ApiWabotManageRoute
  '/api/x/download': typeof ApiXDownloadRoute
  '/api/x/tweets': typeof ApiXTweetsRoute
  '/api/x/user': typeof ApiXUserRoute
  '/api/ytdl/download': typeof ApiYtdlDownloadRoute
  '/api/ytstream/search': typeof ApiYtstreamSearchRoute
  '/api/messages/feed/comment': typeof ApiMessagesFeedCommentRoute
  '/api/messages/feed/like': typeof ApiMessagesFeedLikeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$filename': typeof FilenameRoute
  '/ai-image': typeof AiImageRoute
  '/api-services': typeof ApiServicesRoute
  '/clipboard': typeof ClipboardRoute
  '/cloudify': typeof CloudifyRoute
  '/convert': typeof ConvertRoute
  '/db-console': typeof DbConsoleRoute
  '/gitnetwork': typeof GitnetworkRoute
  '/helium': typeof HeliumRoute
  '/hosting': typeof HostingRoute
  '/instagram': typeof InstagramRoute
  '/israel': typeof IsraelRoute
  '/links': typeof LinksRoute
  '/main': typeof MainRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/note': typeof NoteRouteWithChildren
  '/owner': typeof OwnerRoute
  '/shsdb-console': typeof ShsdbConsoleRoute
  '/tempchat': typeof TempchatRoute
  '/tempmail': typeof TempmailRoute
  '/wabot': typeof WabotRoute
  '/x': typeof XRoute
  '/ytdl': typeof YtdlRoute
  '/ytstream': typeof YtstreamRoute
  '/db/$id': typeof DbIdRoute
  '/db/create': typeof DbCreateRoute
  '/fi/$': typeof FiSplatRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/shsdb/$id': typeof ShsdbIdRoute
  '/shsdb/create': typeof ShsdbCreateRoute
  '/fi/': typeof FiIndexRoute
  '/note/': typeof NoteIndexRoute
  '/api/accounts/create': typeof ApiAccountsCreateRoute
  '/api/accounts/history': typeof ApiAccountsHistoryRoute
  '/api/accounts/login': typeof ApiAccountsLoginRoute
  '/api/chat/room': typeof ApiChatRoomRoute
  '/api/chat/upload': typeof ApiChatUploadRoute
  '/api/cloudify/create': typeof ApiCloudifyCreateRoute
  '/api/cloudify/delete': typeof ApiCloudifyDeleteRoute
  '/api/cloudify/search': typeof ApiCloudifySearchRoute
  '/api/cloudify/songs': typeof ApiCloudifySongsRoute
  '/api/cloudify/update': typeof ApiCloudifyUpdateRoute
  '/api/crossdevice/receive': typeof ApiCrossdeviceReceiveRoute
  '/api/crossdevice/send': typeof ApiCrossdeviceSendRoute
  '/api/fi/download': typeof ApiFiDownloadRoute
  '/api/fi/upload': typeof ApiFiUploadRoute
  '/api/gitnetwork/manage': typeof ApiGitnetworkManageRoute
  '/api/gitnetwork/v1': typeof ApiGitnetworkV1Route
  '/api/image/generate': typeof ApiImageGenerateRoute
  '/api/instagram/download': typeof ApiInstagramDownloadRoute
  '/api/links/manage': typeof ApiLinksManageRoute
  '/api/messages/action': typeof ApiMessagesActionRoute
  '/api/messages/feed': typeof ApiMessagesFeedRouteWithChildren
  '/api/messages/list': typeof ApiMessagesListRoute
  '/api/messages/post': typeof ApiMessagesPostRoute
  '/api/messages/publickey': typeof ApiMessagesPublickeyRoute
  '/api/messages/register': typeof ApiMessagesRegisterRoute
  '/api/messages/send': typeof ApiMessagesSendRoute
  '/api/messages/updatepfp': typeof ApiMessagesUpdatepfpRoute
  '/api/messages/updateprofile': typeof ApiMessagesUpdateprofileRoute
  '/api/pfp/get': typeof ApiPfpGetRoute
  '/api/pfp/remove': typeof ApiPfpRemoveRoute
  '/api/pfp/upload': typeof ApiPfpUploadRoute
  '/api/public/download': typeof ApiPublicDownloadRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/v1/ai': typeof ApiV1AiRoute
  '/api/v1/image': typeof ApiV1ImageRoute
  '/api/v1/instagram': typeof ApiV1InstagramRoute
  '/api/v1/ytv3': typeof ApiV1Ytv3Route
  '/api/wabot/manage': typeof ApiWabotManageRoute
  '/api/x/download': typeof ApiXDownloadRoute
  '/api/x/tweets': typeof ApiXTweetsRoute
  '/api/x/user': typeof ApiXUserRoute
  '/api/ytdl/download': typeof ApiYtdlDownloadRoute
  '/api/ytstream/search': typeof ApiYtstreamSearchRoute
  '/api/messages/feed/comment': typeof ApiMessagesFeedCommentRoute
  '/api/messages/feed/like': typeof ApiMessagesFeedLikeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$filename'
    | '/ai-image'
    | '/api-services'
    | '/clipboard'
    | '/cloudify'
    | '/convert'
    | '/db-console'
    | '/gitnetwork'
    | '/helium'
    | '/hosting'
    | '/instagram'
    | '/israel'
    | '/links'
    | '/main'
    | '/messages'
    | '/more'
    | '/note'
    | '/owner'
    | '/shsdb-console'
    | '/tempchat'
    | '/tempmail'
    | '/wabot'
    | '/x'
    | '/ytdl'
    | '/ytstream'
    | '/db/$id'
    | '/db/create'
    | '/fi/$'
    | '/note/$noteId'
    | '/shsdb/$id'
    | '/shsdb/create'
    | '/fi/'
    | '/note/'
    | '/api/accounts/create'
    | '/api/accounts/history'
    | '/api/accounts/login'
    | '/api/chat/room'
    | '/api/chat/upload'
    | '/api/cloudify/create'
    | '/api/cloudify/delete'
    | '/api/cloudify/search'
    | '/api/cloudify/songs'
    | '/api/cloudify/update'
    | '/api/crossdevice/receive'
    | '/api/crossdevice/send'
    | '/api/fi/download'
    | '/api/fi/upload'
    | '/api/gitnetwork/manage'
    | '/api/gitnetwork/v1'
    | '/api/image/generate'
    | '/api/instagram/download'
    | '/api/links/manage'
    | '/api/messages/action'
    | '/api/messages/feed'
    | '/api/messages/list'
    | '/api/messages/post'
    | '/api/messages/publickey'
    | '/api/messages/register'
    | '/api/messages/send'
    | '/api/messages/updatepfp'
    | '/api/messages/updateprofile'
    | '/api/pfp/get'
    | '/api/pfp/remove'
    | '/api/pfp/upload'
    | '/api/public/download'
    | '/api/public/upload'
    | '/api/v1/ai'
    | '/api/v1/image'
    | '/api/v1/instagram'
    | '/api/v1/ytv3'
    | '/api/wabot/manage'
    | '/api/x/download'
    | '/api/x/tweets'
    | '/api/x/user'
    | '/api/ytdl/download'
    | '/api/ytstream/search'
    | '/api/messages/feed/comment'
    | '/api/messages/feed/like'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$filename'
    | '/ai-image'
    | '/api-services'
    | '/clipboard'
    | '/cloudify'
    | '/convert'
    | '/db-console'
    | '/gitnetwork'
    | '/helium'
    | '/hosting'
    | '/instagram'
    | '/israel'
    | '/links'
    | '/main'
    | '/messages'
    | '/more'
    | '/owner'
    | '/shsdb-console'
    | '/tempchat'
    | '/tempmail'
    | '/wabot'
    | '/x'
    | '/ytdl'
    | '/ytstream'
    | '/db/$id'
    | '/db/create'
    | '/fi/$'
    | '/note/$noteId'
    | '/shsdb/$id'
    | '/shsdb/create'
    | '/fi'
    | '/note'
    | '/api/accounts/create'
    | '/api/accounts/history'
    | '/api/accounts/login'
    | '/api/chat/room'
    | '/api/chat/upload'
    | '/api/cloudify/create'
    | '/api/cloudify/delete'
    | '/api/cloudify/search'
    | '/api/cloudify/songs'
    | '/api/cloudify/update'
    | '/api/crossdevice/receive'
    | '/api/crossdevice/send'
    | '/api/fi/download'
    | '/api/fi/upload'
    | '/api/gitnetwork/manage'
    | '/api/gitnetwork/v1'
    | '/api/image/generate'
    | '/api/instagram/download'
    | '/api/links/manage'
    | '/api/messages/action'
    | '/api/messages/feed'
    | '/api/messages/list'
    | '/api/messages/post'
    | '/api/messages/publickey'
    | '/api/messages/register'
    | '/api/messages/send'
    | '/api/messages/updatepfp'
    | '/api/messages/updateprofile'
    | '/api/pfp/get'
    | '/api/pfp/remove'
    | '/api/pfp/upload'
    | '/api/public/download'
    | '/api/public/upload'
    | '/api/v1/ai'
    | '/api/v1/image'
    | '/api/v1/instagram'
    | '/api/v1/ytv3'
    | '/api/wabot/manage'
    | '/api/x/download'
    | '/api/x/tweets'
    | '/api/x/user'
    | '/api/ytdl/download'
    | '/api/ytstream/search'
    | '/api/messages/feed/comment'
    | '/api/messages/feed/like'
  id:
    | '__root__'
    | '/'
    | '/$filename'
    | '/ai-image'
    | '/api-services'
    | '/clipboard'
    | '/cloudify'
    | '/convert'
    | '/db-console'
    | '/gitnetwork'
    | '/helium'
    | '/hosting'
    | '/instagram'
    | '/israel'
    | '/links'
    | '/main'
    | '/messages'
    | '/more'
    | '/note'
    | '/owner'
    | '/shsdb-console'
    | '/tempchat'
    | '/tempmail'
    | '/wabot'
    | '/x'
    | '/ytdl'
    | '/ytstream'
    | '/db/$id'
    | '/db/create'
    | '/fi/$'
    | '/note/$noteId'
    | '/shsdb/$id'
    | '/shsdb/create'
    | '/fi/'
    | '/note/'
    | '/api/accounts/create'
    | '/api/accounts/history'
    | '/api/accounts/login'
    | '/api/chat/room'
    | '/api/chat/upload'
    | '/api/cloudify/create'
    | '/api/cloudify/delete'
    | '/api/cloudify/search'
    | '/api/cloudify/songs'
    | '/api/cloudify/update'
    | '/api/crossdevice/receive'
    | '/api/crossdevice/send'
    | '/api/fi/download'
    | '/api/fi/upload'
    | '/api/gitnetwork/manage'
    | '/api/gitnetwork/v1'
    | '/api/image/generate'
    | '/api/instagram/download'
    | '/api/links/manage'
    | '/api/messages/action'
    | '/api/messages/feed'
    | '/api/messages/list'
    | '/api/messages/post'
    | '/api/messages/publickey'
    | '/api/messages/register'
    | '/api/messages/send'
    | '/api/messages/updatepfp'
    | '/api/messages/updateprofile'
    | '/api/pfp/get'
    | '/api/pfp/remove'
    | '/api/pfp/upload'
    | '/api/public/download'
    | '/api/public/upload'
    | '/api/v1/ai'
    | '/api/v1/image'
    | '/api/v1/instagram'
    | '/api/v1/ytv3'
    | '/api/wabot/manage'
    | '/api/x/download'
    | '/api/x/tweets'
    | '/api/x/user'
    | '/api/ytdl/download'
    | '/api/ytstream/search'
    | '/api/messages/feed/comment'
    | '/api/messages/feed/like'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilenameRoute: typeof FilenameRoute
  AiImageRoute: typeof AiImageRoute
  ApiServicesRoute: typeof ApiServicesRoute
  ClipboardRoute: typeof ClipboardRoute
  CloudifyRoute: typeof CloudifyRoute
  ConvertRoute: typeof ConvertRoute
  DbConsoleRoute: typeof DbConsoleRoute
  GitnetworkRoute: typeof GitnetworkRoute
  HeliumRoute: typeof HeliumRoute
  HostingRoute: typeof HostingRoute
  InstagramRoute: typeof InstagramRoute
  IsraelRoute: typeof IsraelRoute
  LinksRoute: typeof LinksRoute
  MainRoute: typeof MainRoute
  MessagesRoute: typeof MessagesRoute
  MoreRoute: typeof MoreRoute
  NoteRoute: typeof NoteRouteWithChildren
  OwnerRoute: typeof OwnerRoute
  ShsdbConsoleRoute: typeof ShsdbConsoleRoute
  TempchatRoute: typeof TempchatRoute
  TempmailRoute: typeof TempmailRoute
  WabotRoute: typeof WabotRoute
  XRoute: typeof XRoute
  YtdlRoute: typeof YtdlRoute
  YtstreamRoute: typeof YtstreamRoute
  DbIdRoute: typeof DbIdRoute
  DbCreateRoute: typeof DbCreateRoute
  FiSplatRoute: typeof FiSplatRoute
  ShsdbIdRoute: typeof ShsdbIdRoute
  ShsdbCreateRoute: typeof ShsdbCreateRoute
  FiIndexRoute: typeof FiIndexRoute
  ApiAccountsCreateRoute: typeof ApiAccountsCreateRoute
  ApiAccountsHistoryRoute: typeof ApiAccountsHistoryRoute
  ApiAccountsLoginRoute: typeof ApiAccountsLoginRoute
  ApiChatRoomRoute: typeof ApiChatRoomRoute
  ApiChatUploadRoute: typeof ApiChatUploadRoute
  ApiCloudifyCreateRoute: typeof ApiCloudifyCreateRoute
  ApiCloudifyDeleteRoute: typeof ApiCloudifyDeleteRoute
  ApiCloudifySearchRoute: typeof ApiCloudifySearchRoute
  ApiCloudifySongsRoute: typeof ApiCloudifySongsRoute
  ApiCloudifyUpdateRoute: typeof ApiCloudifyUpdateRoute
  ApiCrossdeviceReceiveRoute: typeof ApiCrossdeviceReceiveRoute
  ApiCrossdeviceSendRoute: typeof ApiCrossdeviceSendRoute
  ApiFiDownloadRoute: typeof ApiFiDownloadRoute
  ApiFiUploadRoute: typeof ApiFiUploadRoute
  ApiGitnetworkManageRoute: typeof ApiGitnetworkManageRoute
  ApiGitnetworkV1Route: typeof ApiGitnetworkV1Route
  ApiImageGenerateRoute: typeof ApiImageGenerateRoute
  ApiInstagramDownloadRoute: typeof ApiInstagramDownloadRoute
  ApiLinksManageRoute: typeof ApiLinksManageRoute
  ApiMessagesActionRoute: typeof ApiMessagesActionRoute
  ApiMessagesFeedRoute: typeof ApiMessagesFeedRouteWithChildren
  ApiMessagesListRoute: typeof ApiMessagesListRoute
  ApiMessagesPostRoute: typeof ApiMessagesPostRoute
  ApiMessagesPublickeyRoute: typeof ApiMessagesPublickeyRoute
  ApiMessagesRegisterRoute: typeof ApiMessagesRegisterRoute
  ApiMessagesSendRoute: typeof ApiMessagesSendRoute
  ApiMessagesUpdatepfpRoute: typeof ApiMessagesUpdatepfpRoute
  ApiMessagesUpdateprofileRoute: typeof ApiMessagesUpdateprofileRoute
  ApiPfpGetRoute: typeof ApiPfpGetRoute
  ApiPfpRemoveRoute: typeof ApiPfpRemoveRoute
  ApiPfpUploadRoute: typeof ApiPfpUploadRoute
  ApiPublicDownloadRoute: typeof ApiPublicDownloadRoute
  ApiPublicUploadRoute: typeof ApiPublicUploadRoute
  ApiV1AiRoute: typeof ApiV1AiRoute
  ApiV1ImageRoute: typeof ApiV1ImageRoute
  ApiV1InstagramRoute: typeof ApiV1InstagramRoute
  ApiV1Ytv3Route: typeof ApiV1Ytv3Route
  ApiWabotManageRoute: typeof ApiWabotManageRoute
  ApiXDownloadRoute: typeof ApiXDownloadRoute
  ApiXTweetsRoute: typeof ApiXTweetsRoute
  ApiXUserRoute: typeof ApiXUserRoute
  ApiYtdlDownloadRoute: typeof ApiYtdlDownloadRoute
  ApiYtstreamSearchRoute: typeof ApiYtstreamSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ytstream': {
      id: '/ytstream'
      path: '/ytstream'
      fullPath: '/ytstream'
      preLoaderRoute: typeof YtstreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ytdl': {
      id: '/ytdl'
      path: '/ytdl'
      fullPath: '/ytdl'
      preLoaderRoute: typeof YtdlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x': {
      id: '/x'
      path: '/x'
      fullPath: '/x'
      preLoaderRoute: typeof XRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wabot': {
      id: '/wabot'
      path: '/wabot'
      fullPath: '/wabot'
      preLoaderRoute: typeof WabotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tempmail': {
      id: '/tempmail'
      path: '/tempmail'
      fullPath: '/tempmail'
      preLoaderRoute: typeof TempmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tempchat': {
      id: '/tempchat'
      path: '/tempchat'
      fullPath: '/tempchat'
      preLoaderRoute: typeof TempchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shsdb-console': {
      id: '/shsdb-console'
      path: '/shsdb-console'
      fullPath: '/shsdb-console'
      preLoaderRoute: typeof ShsdbConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note': {
      id: '/note'
      path: '/note'
      fullPath: '/note'
      preLoaderRoute: typeof NoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/israel': {
      id: '/israel'
      path: '/israel'
      fullPath: '/israel'
      preLoaderRoute: typeof IsraelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosting': {
      id: '/hosting'
      path: '/hosting'
      fullPath: '/hosting'
      preLoaderRoute: typeof HostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helium': {
      id: '/helium'
      path: '/helium'
      fullPath: '/helium'
      preLoaderRoute: typeof HeliumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gitnetwork': {
      id: '/gitnetwork'
      path: '/gitnetwork'
      fullPath: '/gitnetwork'
      preLoaderRoute: typeof GitnetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db-console': {
      id: '/db-console'
      path: '/db-console'
      fullPath: '/db-console'
      preLoaderRoute: typeof DbConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloudify': {
      id: '/cloudify'
      path: '/cloudify'
      fullPath: '/cloudify'
      preLoaderRoute: typeof CloudifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clipboard': {
      id: '/clipboard'
      path: '/clipboard'
      fullPath: '/clipboard'
      preLoaderRoute: typeof ClipboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-services': {
      id: '/api-services'
      path: '/api-services'
      fullPath: '/api-services'
      preLoaderRoute: typeof ApiServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-image': {
      id: '/ai-image'
      path: '/ai-image'
      fullPath: '/ai-image'
      preLoaderRoute: typeof AiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$filename': {
      id: '/$filename'
      path: '/$filename'
      fullPath: '/$filename'
      preLoaderRoute: typeof FilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/': {
      id: '/note/'
      path: '/'
      fullPath: '/note/'
      preLoaderRoute: typeof NoteIndexRouteImport
      parentRoute: typeof NoteRoute
    }
    '/fi/': {
      id: '/fi/'
      path: '/fi'
      fullPath: '/fi/'
      preLoaderRoute: typeof FiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shsdb/create': {
      id: '/shsdb/create'
      path: '/shsdb/create'
      fullPath: '/shsdb/create'
      preLoaderRoute: typeof ShsdbCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shsdb/$id': {
      id: '/shsdb/$id'
      path: '/shsdb/$id'
      fullPath: '/shsdb/$id'
      preLoaderRoute: typeof ShsdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$noteId': {
      id: '/note/$noteId'
      path: '/$noteId'
      fullPath: '/note/$noteId'
      preLoaderRoute: typeof NoteNoteIdRouteImport
      parentRoute: typeof NoteRoute
    }
    '/fi/$': {
      id: '/fi/$'
      path: '/fi/$'
      fullPath: '/fi/$'
      preLoaderRoute: typeof FiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db/create': {
      id: '/db/create'
      path: '/db/create'
      fullPath: '/db/create'
      preLoaderRoute: typeof DbCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db/$id': {
      id: '/db/$id'
      path: '/db/$id'
      fullPath: '/db/$id'
      preLoaderRoute: typeof DbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ytstream/search': {
      id: '/api/ytstream/search'
      path: '/api/ytstream/search'
      fullPath: '/api/ytstream/search'
      preLoaderRoute: typeof ApiYtstreamSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ytdl/download': {
      id: '/api/ytdl/download'
      path: '/api/ytdl/download'
      fullPath: '/api/ytdl/download'
      preLoaderRoute: typeof ApiYtdlDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x/user': {
      id: '/api/x/user'
      path: '/api/x/user'
      fullPath: '/api/x/user'
      preLoaderRoute: typeof ApiXUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x/tweets': {
      id: '/api/x/tweets'
      path: '/api/x/tweets'
      fullPath: '/api/x/tweets'
      preLoaderRoute: typeof ApiXTweetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x/download': {
      id: '/api/x/download'
      path: '/api/x/download'
      fullPath: '/api/x/download'
      preLoaderRoute: typeof ApiXDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wabot/manage': {
      id: '/api/wabot/manage'
      path: '/api/wabot/manage'
      fullPath: '/api/wabot/manage'
      preLoaderRoute: typeof ApiWabotManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/ytv3': {
      id: '/api/v1/ytv3'
      path: '/api/v1/ytv3'
      fullPath: '/api/v1/ytv3'
      preLoaderRoute: typeof ApiV1Ytv3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/instagram': {
      id: '/api/v1/instagram'
      path: '/api/v1/instagram'
      fullPath: '/api/v1/instagram'
      preLoaderRoute: typeof ApiV1InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/image': {
      id: '/api/v1/image'
      path: '/api/v1/image'
      fullPath: '/api/v1/image'
      preLoaderRoute: typeof ApiV1ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/ai': {
      id: '/api/v1/ai'
      path: '/api/v1/ai'
      fullPath: '/api/v1/ai'
      preLoaderRoute: typeof ApiV1AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload': {
      id: '/api/public/upload'
      path: '/api/public/upload'
      fullPath: '/api/public/upload'
      preLoaderRoute: typeof ApiPublicUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download': {
      id: '/api/public/download'
      path: '/api/public/download'
      fullPath: '/api/public/download'
      preLoaderRoute: typeof ApiPublicDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pfp/upload': {
      id: '/api/pfp/upload'
      path: '/api/pfp/upload'
      fullPath: '/api/pfp/upload'
      preLoaderRoute: typeof ApiPfpUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pfp/remove': {
      id: '/api/pfp/remove'
      path: '/api/pfp/remove'
      fullPath: '/api/pfp/remove'
      preLoaderRoute: typeof ApiPfpRemoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pfp/get': {
      id: '/api/pfp/get'
      path: '/api/pfp/get'
      fullPath: '/api/pfp/get'
      preLoaderRoute: typeof ApiPfpGetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/updateprofile': {
      id: '/api/messages/updateprofile'
      path: '/api/messages/updateprofile'
      fullPath: '/api/messages/updateprofile'
      preLoaderRoute: typeof ApiMessagesUpdateprofileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/updatepfp': {
      id: '/api/messages/updatepfp'
      path: '/api/messages/updatepfp'
      fullPath: '/api/messages/updatepfp'
      preLoaderRoute: typeof ApiMessagesUpdatepfpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/send': {
      id: '/api/messages/send'
      path: '/api/messages/send'
      fullPath: '/api/messages/send'
      preLoaderRoute: typeof ApiMessagesSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/register': {
      id: '/api/messages/register'
      path: '/api/messages/register'
      fullPath: '/api/messages/register'
      preLoaderRoute: typeof ApiMessagesRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/publickey': {
      id: '/api/messages/publickey'
      path: '/api/messages/publickey'
      fullPath: '/api/messages/publickey'
      preLoaderRoute: typeof ApiMessagesPublickeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/post': {
      id: '/api/messages/post'
      path: '/api/messages/post'
      fullPath: '/api/messages/post'
      preLoaderRoute: typeof ApiMessagesPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/list': {
      id: '/api/messages/list'
      path: '/api/messages/list'
      fullPath: '/api/messages/list'
      preLoaderRoute: typeof ApiMessagesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/feed': {
      id: '/api/messages/feed'
      path: '/api/messages/feed'
      fullPath: '/api/messages/feed'
      preLoaderRoute: typeof ApiMessagesFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/action': {
      id: '/api/messages/action'
      path: '/api/messages/action'
      fullPath: '/api/messages/action'
      preLoaderRoute: typeof ApiMessagesActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/links/manage': {
      id: '/api/links/manage'
      path: '/api/links/manage'
      fullPath: '/api/links/manage'
      preLoaderRoute: typeof ApiLinksManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instagram/download': {
      id: '/api/instagram/download'
      path: '/api/instagram/download'
      fullPath: '/api/instagram/download'
      preLoaderRoute: typeof ApiInstagramDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image/generate': {
      id: '/api/image/generate'
      path: '/api/image/generate'
      fullPath: '/api/image/generate'
      preLoaderRoute: typeof ApiImageGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gitnetwork/v1': {
      id: '/api/gitnetwork/v1'
      path: '/api/gitnetwork/v1'
      fullPath: '/api/gitnetwork/v1'
      preLoaderRoute: typeof ApiGitnetworkV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gitnetwork/manage': {
      id: '/api/gitnetwork/manage'
      path: '/api/gitnetwork/manage'
      fullPath: '/api/gitnetwork/manage'
      preLoaderRoute: typeof ApiGitnetworkManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fi/upload': {
      id: '/api/fi/upload'
      path: '/api/fi/upload'
      fullPath: '/api/fi/upload'
      preLoaderRoute: typeof ApiFiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fi/download': {
      id: '/api/fi/download'
      path: '/api/fi/download'
      fullPath: '/api/fi/download'
      preLoaderRoute: typeof ApiFiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crossdevice/send': {
      id: '/api/crossdevice/send'
      path: '/api/crossdevice/send'
      fullPath: '/api/crossdevice/send'
      preLoaderRoute: typeof ApiCrossdeviceSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crossdevice/receive': {
      id: '/api/crossdevice/receive'
      path: '/api/crossdevice/receive'
      fullPath: '/api/crossdevice/receive'
      preLoaderRoute: typeof ApiCrossdeviceReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudify/update': {
      id: '/api/cloudify/update'
      path: '/api/cloudify/update'
      fullPath: '/api/cloudify/update'
      preLoaderRoute: typeof ApiCloudifyUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudify/songs': {
      id: '/api/cloudify/songs'
      path: '/api/cloudify/songs'
      fullPath: '/api/cloudify/songs'
      preLoaderRoute: typeof ApiCloudifySongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudify/search': {
      id: '/api/cloudify/search'
      path: '/api/cloudify/search'
      fullPath: '/api/cloudify/search'
      preLoaderRoute: typeof ApiCloudifySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudify/delete': {
      id: '/api/cloudify/delete'
      path: '/api/cloudify/delete'
      fullPath: '/api/cloudify/delete'
      preLoaderRoute: typeof ApiCloudifyDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudify/create': {
      id: '/api/cloudify/create'
      path: '/api/cloudify/create'
      fullPath: '/api/cloudify/create'
      preLoaderRoute: typeof ApiCloudifyCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/upload': {
      id: '/api/chat/upload'
      path: '/api/chat/upload'
      fullPath: '/api/chat/upload'
      preLoaderRoute: typeof ApiChatUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/room': {
      id: '/api/chat/room'
      path: '/api/chat/room'
      fullPath: '/api/chat/room'
      preLoaderRoute: typeof ApiChatRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts/login': {
      id: '/api/accounts/login'
      path: '/api/accounts/login'
      fullPath: '/api/accounts/login'
      preLoaderRoute: typeof ApiAccountsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts/history': {
      id: '/api/accounts/history'
      path: '/api/accounts/history'
      fullPath: '/api/accounts/history'
      preLoaderRoute: typeof ApiAccountsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts/create': {
      id: '/api/accounts/create'
      path: '/api/accounts/create'
      fullPath: '/api/accounts/create'
      preLoaderRoute: typeof ApiAccountsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/feed/like': {
      id: '/api/messages/feed/like'
      path: '/like'
      fullPath: '/api/messages/feed/like'
      preLoaderRoute: typeof ApiMessagesFeedLikeRouteImport
      parentRoute: typeof ApiMessagesFeedRoute
    }
    '/api/messages/feed/comment': {
      id: '/api/messages/feed/comment'
      path: '/comment'
      fullPath: '/api/messages/feed/comment'
      preLoaderRoute: typeof ApiMessagesFeedCommentRouteImport
      parentRoute: typeof ApiMessagesFeedRoute
    }
  }
}

interface NoteRouteChildren {
  NoteNoteIdRoute: typeof NoteNoteIdRoute
  NoteIndexRoute: typeof NoteIndexRoute
}

const NoteRouteChildren: NoteRouteChildren = {
  NoteNoteIdRoute: NoteNoteIdRoute,
  NoteIndexRoute: NoteIndexRoute,
}

const NoteRouteWithChildren = NoteRoute._addFileChildren(NoteRouteChildren)

interface ApiMessagesFeedRouteChildren {
  ApiMessagesFeedCommentRoute: typeof ApiMessagesFeedCommentRoute
  ApiMessagesFeedLikeRoute: typeof ApiMessagesFeedLikeRoute
}

const ApiMessagesFeedRouteChildren: ApiMessagesFeedRouteChildren = {
  ApiMessagesFeedCommentRoute: ApiMessagesFeedCommentRoute,
  ApiMessagesFeedLikeRoute: ApiMessagesFeedLikeRoute,
}

const ApiMessagesFeedRouteWithChildren = ApiMessagesFeedRoute._addFileChildren(
  ApiMessagesFeedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilenameRoute: FilenameRoute,
  AiImageRoute: AiImageRoute,
  ApiServicesRoute: ApiServicesRoute,
  ClipboardRoute: ClipboardRoute,
  CloudifyRoute: CloudifyRoute,
  ConvertRoute: ConvertRoute,
  DbConsoleRoute: DbConsoleRoute,
  GitnetworkRoute: GitnetworkRoute,
  HeliumRoute: HeliumRoute,
  HostingRoute: HostingRoute,
  InstagramRoute: InstagramRoute,
  IsraelRoute: IsraelRoute,
  LinksRoute: LinksRoute,
  MainRoute: MainRoute,
  MessagesRoute: MessagesRoute,
  MoreRoute: MoreRoute,
  NoteRoute: NoteRouteWithChildren,
  OwnerRoute: OwnerRoute,
  ShsdbConsoleRoute: ShsdbConsoleRoute,
  TempchatRoute: TempchatRoute,
  TempmailRoute: TempmailRoute,
  WabotRoute: WabotRoute,
  XRoute: XRoute,
  YtdlRoute: YtdlRoute,
  YtstreamRoute: YtstreamRoute,
  DbIdRoute: DbIdRoute,
  DbCreateRoute: DbCreateRoute,
  FiSplatRoute: FiSplatRoute,
  ShsdbIdRoute: ShsdbIdRoute,
  ShsdbCreateRoute: ShsdbCreateRoute,
  FiIndexRoute: FiIndexRoute,
  ApiAccountsCreateRoute: ApiAccountsCreateRoute,
  ApiAccountsHistoryRoute: ApiAccountsHistoryRoute,
  ApiAccountsLoginRoute: ApiAccountsLoginRoute,
  ApiChatRoomRoute: ApiChatRoomRoute,
  ApiChatUploadRoute: ApiChatUploadRoute,
  ApiCloudifyCreateRoute: ApiCloudifyCreateRoute,
  ApiCloudifyDeleteRoute: ApiCloudifyDeleteRoute,
  ApiCloudifySearchRoute: ApiCloudifySearchRoute,
  ApiCloudifySongsRoute: ApiCloudifySongsRoute,
  ApiCloudifyUpdateRoute: ApiCloudifyUpdateRoute,
  ApiCrossdeviceReceiveRoute: ApiCrossdeviceReceiveRoute,
  ApiCrossdeviceSendRoute: ApiCrossdeviceSendRoute,
  ApiFiDownloadRoute: ApiFiDownloadRoute,
  ApiFiUploadRoute: ApiFiUploadRoute,
  ApiGitnetworkManageRoute: ApiGitnetworkManageRoute,
  ApiGitnetworkV1Route: ApiGitnetworkV1Route,
  ApiImageGenerateRoute: ApiImageGenerateRoute,
  ApiInstagramDownloadRoute: ApiInstagramDownloadRoute,
  ApiLinksManageRoute: ApiLinksManageRoute,
  ApiMessagesActionRoute: ApiMessagesActionRoute,
  ApiMessagesFeedRoute: ApiMessagesFeedRouteWithChildren,
  ApiMessagesListRoute: ApiMessagesListRoute,
  ApiMessagesPostRoute: ApiMessagesPostRoute,
  ApiMessagesPublickeyRoute: ApiMessagesPublickeyRoute,
  ApiMessagesRegisterRoute: ApiMessagesRegisterRoute,
  ApiMessagesSendRoute: ApiMessagesSendRoute,
  ApiMessagesUpdatepfpRoute: ApiMessagesUpdatepfpRoute,
  ApiMessagesUpdateprofileRoute: ApiMessagesUpdateprofileRoute,
  ApiPfpGetRoute: ApiPfpGetRoute,
  ApiPfpRemoveRoute: ApiPfpRemoveRoute,
  ApiPfpUploadRoute: ApiPfpUploadRoute,
  ApiPublicDownloadRoute: ApiPublicDownloadRoute,
  ApiPublicUploadRoute: ApiPublicUploadRoute,
  ApiV1AiRoute: ApiV1AiRoute,
  ApiV1ImageRoute: ApiV1ImageRoute,
  ApiV1InstagramRoute: ApiV1InstagramRoute,
  ApiV1Ytv3Route: ApiV1Ytv3Route,
  ApiWabotManageRoute: ApiWabotManageRoute,
  ApiXDownloadRoute: ApiXDownloadRoute,
  ApiXTweetsRoute: ApiXTweetsRoute,
  ApiXUserRoute: ApiXUserRoute,
  ApiYtdlDownloadRoute: ApiYtdlDownloadRoute,
  ApiYtstreamSearchRoute: ApiYtstreamSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
